# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.31
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _quad_storage
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


class QuadIndex(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, QuadIndex, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, QuadIndex, name)
    __repr__ = _swig_repr
    __swig_setmethods__["kb"] = _quad_storage.QuadIndex_kb_set
    __swig_getmethods__["kb"] = _quad_storage.QuadIndex_kb_get
    if _newclass:kb = _swig_property(_quad_storage.QuadIndex_kb_get, _quad_storage.QuadIndex_kb_set)
    def __init__(self, *args): 
        this = _quad_storage.new_QuadIndex(*args)
        try: self.this.append(this)
        except: self.this = this
    def importFile(*args): return _quad_storage.QuadIndex_importFile(*args)
    def query(*args): return _quad_storage.QuadIndex_query(*args)
    def close(*args): return _quad_storage.QuadIndex_close(*args)
    def size(*args): return _quad_storage.QuadIndex_size(*args)
    def isOpen(*args): return _quad_storage.QuadIndex_isOpen(*args)
    def __str__(*args): return _quad_storage.QuadIndex___str__(*args)
    __swig_destroy__ = _quad_storage.delete_QuadIndex
    __del__ = lambda self : None;
QuadIndex_swigregister = _quad_storage.QuadIndex_swigregister
QuadIndex_swigregister(QuadIndex)



